#!/bin/bash
curl -L -O https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_macos.universal.zip
unzip Godot_v4.3-stable_macos.universal.zip
mv Godot.app ~/goinfre
rm -fr Godot_v4.3-stable_macos.universal.zip
alias godot='./goinfre/Godot.app/Contents/MacOS/Godot'
